name: On PRs - meson

on: pull_request

concurrency:
  group: ${{github.workflow}}-${{github.head_ref}}
  cancel-in-progress: true

jobs:
  Ubuntu:
    runs-on: ubuntu-20.04
    name: Linux-GCC${{matrix.cxx}}-deps=${{matrix.deps}}
    strategy:
      matrix:
        cxx: ['7', '10']
        deps: ['enabled', 'disabled']
    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: |
          sudo apt install -y g++-${{matrix.cxx}} gettext libgtk-3-dev libchamplain-0.12-dev libchamplain-gtk-0.12-dev libgspell-1-dev libheif-dev libpoppler-glib-dev libomp-dev pandoc libopenjp2-7-dev libavcodec-dev libavfilter-dev libavutil-dev libffmpegthumbnailer-dev libgtk-3-bin shellcheck xvfb
          python3 -m pip install meson ninja

      - name: Compile and Test
        env:
          CXX: g++-${{matrix.cxx}}
        run: |
          meson setup "${{github.workspace}}/build" -Dauto_features=${{matrix.deps}} -Dwarning_level=3 -Djpegxl=disabled -Dlibraw=disabled -Dexiv2:curl=disabled -Dlibarchive:xattr=disabled -Dlibarchive:bz2lib=disabled -Dlibarchive:libb2=disabled -Dlibarchive:acl=disabled
          meson compile -C "${{github.workspace}}/build" --verbose
          meson test -C "${{github.workspace}}/build" --verbose
  Ubuntu-clang:
    runs-on: ubuntu-20.04
    name: Linux-Clang${{matrix.cxx}}-deps=${{matrix.deps}}
    strategy:
      matrix:
        cxx: ['7', '12']
        deps: ['enabled', 'disabled']
    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: |
          sudo apt install -y clang-${{matrix.cxx}} libc++abi-${{matrix.cxx}}-dev libc++-${{matrix.cxx}}-dev lld-${{matrix.cxx}} gettext libgtk-3-dev libchamplain-0.12-dev libchamplain-gtk-0.12-dev libgspell-1-dev libheif-dev libpoppler-glib-dev libomp-dev pandoc libopenjp2-7-dev libavcodec-dev libavfilter-dev libavutil-dev libffmpegthumbnailer-dev libgtk-3-bin shellcheck xfvb
          python3 -m pip install meson ninja

      - name: Compile and Test
        env:
          CXX: clang++-${{matrix.cxx}}
          CXXFLAGS: -stdlib=libc++
          CXX_LD: lld-${{matrix.cxx}}
        run: |
          meson setup "${{github.workspace}}/build" -Dauto_features=${{matrix.deps}} -Dwarning_level=3 -Dcpp_std=c++20 -Djpegxl=disabled -Dlibraw=disabled -Dexiv2:curl=disabled -Dlibarchive:xattr=disabled -Dlibarchive:bz2lib=disabled -Dlibarchive:libb2=disabled -Dlibarchive:acl=disabled
          meson compile -C "${{github.workspace}}/build" --verbose
          meson test -C "${{github.workspace}}/build" --verbose
  MacOS:
    runs-on: macos-latest
    name: macOS-deps=${{matrix.deps}}
    strategy:
      matrix:
        deps: ['enabled', 'disabled']
    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: |
          brew install gdk-pixbuf gtk+3 libarchive djvulibre poppler gspell ffmpeg@4
          python3 -m pip install meson ninja

      - name: Compile and Test
        run: |
          meson setup "${{github.workspace}}/build" -Dauto_features=${{matrix.deps}} -Dwarning_level=3 -Dpkg_config_path=/usr/local/opt/libarchive/lib/pkgconfig,/usr/local/opt/ffmpeg@4/lib/pkgconfig -Dgps-map=disabled -Dspell=disabled -Dvideothumbnailer=disabled
          meson compile -C "${{github.workspace}}/build" --verbose
          meson test -C "${{github.workspace}}/build" --verbose
